server:
  port: 8080
spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          base-uri: https://quilmeswallet.b2clogin.com/quilmeswallet.onmicrosoft.com/
          credential:
            client-id: e7ea2c13-75cc-4e49-aacc-8d4d587ce077
            client-secret: 'pXG8Q~QIT64QHG2x1DAk3oIHfGFOVOmD2ihK3aNT'
          login-flow: sign-up-or-sign-in
          logout-success-url: http://localhost:8081/
          user-flows:
            sign-up-or-sign-in: B2C_1_AbiWallet
            profile-edit: B2C_1_AbiWallet_Edit
            password-reset: B2C_1_AbiWallet_Reset
          #user-name-attribute-name: <your-user-name-attribute-name>